//
//  ToDoTasksListWorker.swift
//  CleanSwiftExample
//
//  Created by Local User on 6/6/17.
//  Copyright (c) 2017 Local User. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ToDoTasksListWorker{
    // MARK: Business Logic
    
    var myStruct : [ToDoTasksList.Task] = []
    
    func multiply(number: String) -> Int{
        return Int(number)! * 2
    }
    
    func getArrayTasks() -> [ToDoTasksList.Task]
    {
        if myStruct.count == 0
        {
            myStruct.append(ToDoTasksList.Task(text: "TO DO #1", counter : 1))
            myStruct.append(ToDoTasksList.Task(text: "TO DO #2", counter : 2))
            myStruct.append(ToDoTasksList.Task(text: "TO DO #3", counter : 3))
        }
        return myStruct
    }
}
